### ISSUE TITLE
Allow pointing to and executing a SQL script on run

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/mssql-docker#11]
For scenarios where you might want to create logins, run some test/initial data population script, etc. it would be nice to be able to point to a sql script file and have that be executed by the entrypoint script after the sqlservr process is started.

**Comment by rfaaberg** [comment]
That would be awesome, I can already see a great use-case for this image for spinning up dev databases. I hacked in that functionality with a modified start.ps1 script that I'd open a PR for but sounds like this repo isn't used to generate the image.

**Comment by twright-msft** [comment]
Right, we don't build out of this repo.  Feel free to share what you would do by creating a new Dockerfile and entrypoint.sh on your github and shoot us a link to that and the image on Docker Hub.  

Here is an implementations that I did last week for a demo that I did in a presentation at a conference.
https://github.com/twright-msft/mssql-node-docker-demo-app

**Comment by twright-msft** [comment]
Here is an example of executing a SQL script at run time.
https://github.com/twright-msft/mssql-node-docker-demo-app

That's really a lot more complicated than it needs to be though.

**Comment by twright-msft** [comment]
FYI - We released CTP 1.4 today.  This release of the mssql-server-linux image now includes the mssql-tools package (sqlcmd and bcp) in it.

Executing sqlcmd as part of the entrypoint.sh script can be used for this kind of scenario for now.  Since this is such a commonplace requirement we want to make it easier in the future, but sqlcmd will provide a reasonable option until then.

**Comment by shanegenschaw** [comment]
I created a [pull request](https://github.com/Microsoft/mssql-docker/pull/60) based on the example in the [demo](https://github.com/twright-msft/mssql-node-docker-demo-app) mentioned above, implemented in a similar fashion as the [mysql](https://hub.docker.com/_/mysql/) image.

Hope this is useful and considered for inclusion.

**Comment by jvitor83** [comment]
As a workaround, maybe this can be helpfull:
```
  flyway:
    image: boxfuse/flyway
    command: -c "sleep 30; flyway migrate -user=sa -password=$${SA_PASSWORD} -url=jdbc:sqlserver://sqlserver:1433;databaseName=$${DATABASE}"
    entrypoint: sh
    volumes:
      - ./sql:/flyway/sql
    environment:
      SA_PASSWORD: P@ssw0rd
      DATABASE: MyDatabase

  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1433:1433
    entrypoint: sh
    command: -c '/opt/mssql/bin/sqlservr & /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -U sa -P $${SA_PASSWORD} -d tempdb -q "CREATE DATABASE $${DATABASE}"; wait'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: P@ssw0rd
      DATABASE: MyDatabase
```

**Comment by rmoff** [comment]
Here's another workaround, this one will execute all the SQL files in a mounted folder: 

```
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      - SA_PASSWORD=Admin123
      - ACCEPT_EULA=Y
    volumes:
     - ./data/mssql:/scripts/
    command:
      - /bin/bash
      - -c 
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # Wait 30 seconds for it to be available
        # (lame, I know, but there's no nc available to start prodding network ports)
        sleep 30
        # Run every script in /scripts
        # TODO set a flag so that this is only done once on creation, 
        #      and not every time the container runs
        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
        done
        # So that the container doesn't shut down, sleep this thread
        sleep infinity
```
