### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by mrfuxi** [Microsoft/mssql-docker#133]
Would it be possible to implement Docker's HEALTHCHECK command?

**Comment by twright-msft** [comment]
Yeah, now that we have sqlcmd in the image this should be much easier.  I'll put it on our backlog internally.  If you need something sooner, I'd suggest creating your own image FROM ours and specifying a HEALTCHECK that uses sqlcmd with -q to execute a simple query periodically like 'SELECT 1'.

**Comment by sangohan** [comment]
I too am having an issue where the docker image crashes, but continues to output lines of logging, which prevents my internal hung-build-killer tool to detect that something went wrong. 

> 2017-09-06 09:50:11.21 spid90      Timeout occurred while waiting for latch: class 'LOG_MANAGER', id 00000005ED740BB0, type 4, Task 0x00000005EB49B088 : 0, waittime 71400 seconds, flags 0x1a, owning task 0x00000005EB492CA8. Continuing to wait.
2017-09-06 09:50:25.26 spid89      Timeout occurred while waiting for latch: class 'LOG_MANAGER', id 00000005ED740BB0, type 4, Task 0x00000005EEDE7088 : 0, waittime 71400 seconds, flags 0x1a, owning task 0x00000005EB492CA8. Continuing to wait.
2017-09-06 09:51:25.25 spid84      Timeout occurred while waiting for latch: class 'LOG_MANAGER', id 00000005ED740BB0, type 4, Task 0x00000005E800DC28 : 0, waittime 71400 seconds, flags 0x1a, owning task 0x00000005EB492CA8. Continuing to wait.

having a healthcheck mechanism in the case of this would be great.

**Comment by manicmonkey** [comment]
I get the same crash / error when using netcat to ascertain when the process has started listening on port 1433

**Comment by axelfontaine** [comment]
This is super useful in order to avoid having to develop custom poll and wait script to check whether the DB is up in order to be able to start other activities.

**Comment by krkabol** [comment]
Dockerfile:

```Dockerfile
FROM microsoft/mssql-server-linux
HEALTHCHECK --interval=10s --timeout=3s --start-period=10s --retries=10 \
    CMD sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT 1" || exit 1
```

**Comment by djechelon** [comment]
It should be

`CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT 1" || exit 1`

Because sqlcmd is not on PATH

**Comment by raczeja** [comment]
Is there a simple way to use HEALTHCHECK?
I use this piece of code, but maybe you can advise something simpler?
`
do	
{
	$JSON=docker inspect --format='{{json .State.Health}}'  sqlserver-container |  Out-String | ConvertFrom-Json
	Write-Host HEALTHCHECK: $JSON.Status.ToString() sqlserver-container
	Start-Sleep -s 10
}
Until ($JSON.Status.ToString() -eq 'healthy')
`

**Comment by tinohager** [comment]
```
version: "3.4"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Secure-Password.1234"
            ACCEPT_EULA: "Y"
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
            interval: 10s
            timeout: 3s
            retries: 10
            start_period: 10s
```

**Comment by mrlioncub** [comment]
Everything that is written above must be changed:
required with the option: **-b** 
and I recommend using the option: **-o /dev/null**
in docker-compose.yaml
```
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
```
in Dockerfile:
```
CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT 1" -b -o /dev/null || exit 1
```

**Comment by raschmitt** [comment]
I'm curious here, why do we need to have `exit 1` if `sqlcmd -Q` already has a built-in exit?

```
 -Q "cmdline query" (and exit)  
```

https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15#syntax

**Comment by mrlioncub** [comment]
Yes, `exit 1` is not needed. [Updated](https://github.com/microsoft/mssql-docker/issues/133#issuecomment-796472416)

**Comment by ls42** [comment]
These solution don't take into account that during database migration **after an update, the database can be locked for several minutes**. To the developers: Is it possible to take that into account? Does sql-server have an idiomatic way to determine that it is currently upgrading databases? Are you maybe working on a HEALTHCHECK command that is working with that scenario?

The best idea so far to work around this is to add `--start-period=10m` to the healthcheck.

**Comment by leomelzer** [comment]
Thanks @mrlioncub 🎉 I was searching for a solution for using the image in a GitHub Action and the healthcheck wasn't working...thankfully Google found your comment.

Passing `-b -o /dev/null` solved the issue for me. Sharing for future reference: 

```yml
name: CI

on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        env:
            DB_USER: SA
            DB_PASSWORD: yourStrongP@ssword
            DB_NAME: your_db

        services:
            mssql:
                image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
                env:
                    ACCEPT_EULA: Y
                    SA_PASSWORD: ${{ env.DB_PASSWORD }}
                    MSSQL_PID: Express
                    DB_USER: ${{ env.DB_USER }}
                    DB_NAME: ${{ env.DB_NAME }}
                ports:
                    - 1433/tcp
                options: >-
                    --health-cmd "/opt/mssql-tools/bin/sqlcmd -U $DB_USER -P $SA_PASSWORD -Q 'select 1' -b -o /dev/null"
                    --health-interval 60s
                    --health-timeout 30s
                    --health-start-period 20s
                    --health-retries 3

        steps:
            - name: Create Database
              run: |
                  docker exec $(docker ps -alq) /opt/mssql-tools/bin/sqlcmd -U "$DB_USER" -P "$DB_PASSWORD" -Q "CREATE DATABASE $DB_NAME;"

            - uses: actions/checkout@v2

            - name: Setup Node Package Cache
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install
              run: |
                  npm ci --prefer-offline --no-audit

            - name: Test
              env:
                  DB_HOST: localhost
                  DB_PORT: ${{ job.services.mssql.ports[1433] }}
                  DB_USER: ${{ env.DB_USER }}
                  DB_PASSWORD: ${{ env.DB_PASSWORD }}
                  DB_NAME: ${{ env.DB_NAME }}
              run: |
                  npm test
```
