### ISSUE TITLE
Fatal Error with Reason 0x00000006 after a while on linux

### ISSUE THREAD

**Issue by hbobenicio** [Microsoft/mssql-docker#264]
I'm starting a mssql server instance from [this docker file with FTS module](https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile) and this docker-compose.yml:

```
version: '3.1'
services:
  mssql:
    build:
      context: ./services/mssql
    image: 'my-mssql:2017'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MY@password
      - SA_PASSWORD=MY@password
    volumes:
      - ./services/mssql/volumes/data:/var/opt/mssql
```

The issue that I'm facing is that, after a while (I didn't find a pattern yet, but it happens from times to times... last time the database was in IDLE with just a [DBeaver](https://dbeaver.jkiss.org/) connection), the server crashes with a fatal error as follows:

```
mssql_1      | This program has encountered a fatal error and cannot continue running.
mssql_1      | The following diagnostic information is available:
mssql_1      | 
mssql_1      |        Reason: 0x00000006
mssql_1      |        Status: 0xc0000005
mssql_1      |       Message: Last Chance
mssql_1      |       Address: 0x6a446912
mssql_1      |    Parameters: 0x802cef270
   Stacktrace: 000000006a4e84f6 000000006a43fb1e 000000006a43f9ca 
mssql_1      |                000000006a518473 000000006a446912 
      Process: 9 - sqlservr
mssql_1      |        Thread: 175 (application thread 0x1288)
mssql_1      |   Instance Id: 7eb1810a-0fbe-42f1-bb07-a0f20f7f3dcf
mssql_1      |      Crash Id: bec85ffc-9907-4f7b-a7bd-bd17e0c90561
mssql_1      |   Build stamp: 0fa9143612e88b9b2379174bbdc492bbfae2bec2f0278445d22e11dd124604ab
mssql_1      | 
mssql_1      | Capturing core dump and information...
mssql_1      | No journal files were found.
mssql_1      | No journal files were found.
mssql_1      | Attempting to capture a dump with paldumper
mssql_1      | WARNING: Capture attempt failure detected
mssql_1      | Attempting to capture a filtered dump with paldumper
mssql_1      | WARNING: Attempt to capture dump failed.  Reference /var/opt/mssql/log/core.sqlservr.9.temp/log/paldumper-debug.log for details
mssql_1      | Attempting to capture a dump with gdb
mssql_1      | WARNING: Unable to capture crash dump with GDB. You may need to
mssql_1      | allow ptrace debugging, enable the CAP_SYS_PTRACE capability, or
mssql_1      | run as root.
```

[this error reasons table](https://msdn.microsoft.com/en-us/library/cc231199.aspx) (am I looking at the correct table?) points that:

Reason: 0x00000006 - The handle is invalid.
Message: Last Chance

I have no clue what is going on... somebody facing the same issue? Any tips about it?

PS.:
I'm on Ubuntu 16.04.3 LTS (x86_64)
