### ISSUE TITLE
Named volumes on docker for windows prevent login

### ISSUE THREAD

**Issue by joshampton** [Microsoft/mssql-docker#320]
When running the following docker-compose file I'm able to exec a sqlcmd on the `sql` container but I'm unable to exec a sql command on the `sql_named_volume` container. 

```
version: '3'

services:
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: ComplexPassword123
    container_name: sql
    volumes:
      - /var/opt/mssql
  sql_named_volume:
    image: microsoft/mssql-server-linux:2017-latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: ComplexPassword123
    container_name: sql_named_volume
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
```

`docker exec -it sql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ComplexPassword123` works as expected

`docker exec -it sql_named_volume /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ComplexPassword123` returns `Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'sa'..`

Docker version: `Docker version 17.12.1-ce, build 7390fc6`
Docker Compose version: `docker-compose version 1.19.0, build 9e633ef`
