### ISSUE TITLE
SSMS restore database error 31 in docker

### ISSUE THREAD

**Issue by DrRee** [Microsoft/mssql-docker#391]
**### SSMS restore database error 31**

I have issue with restore backup from database inside SSMS. In SSMS, I select Database -> restore database -> Device -> Select backup devices -> Add -> bb.bak after that I click on added file into list and I want to see "Contents" error bellow "Error" and if I go next I'm not able to restore my database.
SSMS version: 17.9  

**### Error:**
```
TITLE: Microsoft.SqlServer.Smo

System.Data.SqlClient.SqlError: Read on "/var/opt/mssql/backup/back.bak" failed: 31(A device attached to the system is not functioning.)

For help, click: http://go.microsoft.com/fwlinkProdName=Microsoft+SQL+Server&ProdVer=14.0.17285.0((SSMS_Rel_17_4).180821-0238)&LinkId=20476
```

I have tried to solve this error with full rights on whole path to backup dir inside the docker but it didn't help. After ls -la /var/opt/mssql/backup everything was setup to 777 (see output below).
**My docker-compose.yml see below:**
```
version: "3.1"
services:
  db:
    image: "microsoft/mssql-server-linux"
    container_name: mssql-server
    environment:
      SA_PASSWORD: "123456Aa+"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
     - ./database/backup:/var/opt/mssql/backup
    command: >
      bash -c "chmod -R 777 /var/opt/mssql/backup/* && /opt/mssql/bin/sqlservr" 
    ports:
     - "192.168.99.100:6000:1433"
```

**### ls -la /var/opt/mssql/backup** 
```
mssql-server | total 6900
mssql-server | drwxrwxrwx 1 1000 staff       0 Nov  8 12:06 .
mssql-server | drwxr-xr-x 3 root root     4096 Nov  8 15:25 ..
mssql-server | -rwxrwxrwx 1 1000 staff    2413 Nov  8 12:06 back.sql
mssql-server | -rwxrwxrwx 1 1000 staff 7056896 Nov  8 12:06 back.bak
```
