### ISSUE TITLE
Some guidance for docker setup for php / mssql / nginx

### ISSUE THREAD

**Issue by gertvdb** [Microsoft/mssql-docker#425]
Hi,

I'm trying to setup a docker environment for a legacy project in symfony 1 that uses a mssql database.
I managed to setup the mssql database by using the `microsoft/mssql-server-linux` image. 

But I keep getting problems setting up the php container. I've read several issue and tutorials but none of them worked entirely or I'm just not getting it, since I not used to working with mssql. 

Below is my docker-compose file. So what I'm trying to do is setup a container for the database (mssql), a container for the application (php) and a container to serve the application (nginx).
 I will also need to be able to run propel from the php container. 

With this setup I keep getting the php container  to exit with code 0 and this also stops the nginx container since it depends on php. 

I was hoping some advanced docker user could point me in the right direction to get everything setup cause i'm getting quite hopeless :)

```
version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "${DOCKER_PROJECT_NAME}_mssql"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: $DOCKER_DATABASE_PASS
    ports:
    - "1433:1433"
    volumes:
    - mssql-volume:/var/opt/mssql

  php:
    container_name: "${DOCKER_PROJECT_NAME}_php"
    image: lbosqmsft/php-mssql
    environment:
      DB_HOST: $DOCKER_DATABASE_HOST
      DB_USER: $DOCKER_DATABASE_USER
      DB_PASSWORD: $DOCKER_DATABASE_PASS
      DB_NAME: $DOCKER_DATABASE_NAME
      DB_DRIVER: mssql
    volumes:
    - ./:/var/www/html

  nginx:
    image: wodby/nginx:1.15-5.0.11
    container_name: "${DOCKER_PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: php
      NGINX_INDEX_FILE: admin_dev.php
    volumes:
    - ./:/var/www/html
    labels:
    - 'traefik.backend=${DOCKER_PROJECT_NAME}_nginx'
    - 'traefik.port=80'
    - 'traefik.frontend.rule=Host:${DOCKER_PROJECT_URL}'

  portainer:
    image: portainer/portainer
    container_name: "${DOCKER_PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - 'traefik.backend=${DOCKER_PROJECT_NAME}_portainer'
    - 'traefik.port=9000'
    - 'traefik.frontend.rule=Host:portainer.${DOCKER_PROJECT_URL}'

  traefik:
    image: traefik
    container_name: "${DOCKER_PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
    - '${DOCKER_PORT}:80'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mssql-volume:
```
