### ISSUE TITLE
BULK INSERT: "Referenced external data source "(null)" not found" when pointing to local file

### ISSUE THREAD

**Issue by migajek** [Microsoft/mssql-docker#432]
I'm running an MS SQL instance in Docker, mounted a volume with CSV files inside (see docker-compose)

```
services:
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "<pass>"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        volumes:
            - ../test-data:/home/test-data
```

the volume is mounted correctly:

```
$ docker-compose exec db sh -c 'ls /home/test-data'
Advisors.csv
```

now when I issue the following query:

```
BULK INSERT Advisors                 
FROM 'C:\home\test-data\Advisors.csv'            
WITH                                       
(FORMAT = 'CSV')
```

I get the error: `Referenced external data source "(null)" not found`

Please note I've tried 'home/test-data/Advisors.csv' at first, but then found the StackOverflow answer pointing out I should convert it to Windows-styled path with "C:" as a root placeholder 
https://stackoverflow.com/a/41865509
