### ISSUE TITLE
mssql-server-windows-express does not exit properly

### ISSUE THREAD

**Issue by LlamaNL** [microsoft/mssql-docker#458]
using Docker for Windows

After running mssql-server-windows-express for a while and stopping the container with `docker-compose down` the shut down sequence hangs on closing the mssql-server-windows-express container. I've tried killing the container but that locks up the terminal. Only a restart of the docker service gets me out of this.

`docker-compose.yml`
```
version: '3.7'
services:
  db:
    image: microsoft/mssql-server-windows-express
    
    environment:
      sa_password: "<password>"
      ACCEPT_EULA: "Y"
      
    ports:
      - "8003:1433"
    build:
      context: .
      dockerfile: mssql.dockerfile

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: mcr.microsoft.com/dotnet/framework/aspnet:4.8
    #volumes:
    #  - .:C:/inetpub/wwwroot
    ports: 
      - "8080:80"
      - "8081:443"
      - "4022:4022"
```

`mssql.dockerfile`
```
# escape=`

FROM microsoft/mssql-server-windows-express

#set shell
SHELL ["powershell.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#make temp folder
RUN mkdir C:\database

#copy database backup file to container
COPY MNGDB.bak C:\database\MNGDB.bak

#replace startup script
COPY start.ps1 C:\
```

start.ps1 has been modified to run a restore query before reading the log info
`sqlcmd -S localhost -U sa -P <password> -Q "USE [master] RESTORE DATABASE [MNGDB] FROM DISK='C:\database\MNGDB.bak' WITH MOVE 'MNGDB_Test' TO 'c:\database\MNGDB.mdf', MOVE 'MNGDB_Test_log' TO 'c:\database\MNGDB.ldf'"`
