### ISSUE TITLE
Unable to authenticate when using persistent volume

### ISSUE THREAD

**Issue by RValeye** [microsoft/mssql-docker#508]
Hi,

I have an issue with a freshly pulled image.

My laptop is running on Manjaro, client and server version of Docker is : `19.03.1-ce`

I'm using docker-compose as follows :
```yaml
version: '3'
services:
  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "!ThisIsAT3sT"
      TZ: Europe/Paris
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql:
```

When I run `docker-compose up` this, I'm unable to login via SA : 
![image](https://user-images.githubusercontent.com/16175245/65694834-c48f5000-e076-11e9-800d-7cc3592b36e0.png)

However, if I remove the persistent volume definition in my `sqlsrv` service, I'm able to log in with SA.
![image](https://user-images.githubusercontent.com/16175245/65695056-1a63f800-e077-11e9-9104-ac743fc3608e.png)

Is there something I'm missing in the configuration ?

Thank you for your help.
