### ISSUE TITLE
No such file or directory K8s Docker for Windows

### ISSUE THREAD

**Issue by TheLever** [microsoft/mssql-docker#535]
Using mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04 I am trying to deploy SQL Server to my local cluster. For some reason it immediately fails with a bug check error (0x00000006) and an error that a file is not found. It eludes me what file is missing. The relevant parts of my yaml are as follows below. How can I diagnose what file is missing, if any?

```
apiVersion: v1
kind: PersistentVolume
metadata:
 name: mssqldb
 labels:
   type: local
spec:
 storageClassName: mssql-storage
 capacity:
   storage: 100Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /C/K8sMounts/Datastore
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mssql-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssqldb-claim
spec:
  storageClassName: mssql-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
...
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 1433
              protocol: TCP
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Sq1Sup3r"
          - name: MSSQL_PID
            value: "Developer"
          volumeMounts:
          - name: mssqldb
            mountPath: /var/opt/mssql
```
