### ISSUE TITLE
Error during startup: /proc/10/maps: Permission denied

### ISSUE THREAD

**Issue by collinsauve** [microsoft/mssql-docker#538]
Hello!  I am attempting to update from the `microsoft/mssql-server-linux:2017-CU8` image to `mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04`.    I get an error during startup that has a lot of "Permission denied" on various `/proc` files.

I am using Docker for Windows with a Docker Compose file (some paths/password redacted):

```
version: '3'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    restart: always
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password123
     - MSSQL_PID=Developer
    volumes:
     - c:\\ProgramData\\myfolder\\sql\\:/var/opt/mssql/
    ports:
     - "11433:1433"
networks:
  default:
    external:
      name: mynetwork
```

Full log is attached.

[log.txt](https://github.com/microsoft/mssql-docker/files/3903170/log.txt)
