### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.`

### ISSUE THREAD

**Issue by lmagalhaes1989** [microsoft/mssql-docker#581]
Hi guys, I'm developing a small containerized app in **.Net Core 3.1.1** with connection to an mssql database in docker and I'm facing an odd behaviour... After I stop the containers and then issue the commands **docker-compose build; docker-compose up** sometimes (not always) I'm facing this error:

`web_1  | crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
web_1  |       Application startup exception
web_1  | Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.`

This is my docker-compose.yml file
`version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        command:
            - "sleep 5;"
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"`

But if I restart docker the database container starts smoothly again...
Any ideas what the issue might be?
I'm using Docker for windows.

Thanks in advance

**Comment by dbamaster** [comment]
Hello there,

I did my best to re-format your docker-compose.yml, this is what you current have:

```yaml
version: "3"
services:
    web:
      build: . 
      ports:
          - "8000:80"
      depends_on:
          - db
      command: 
          - "sleep 5;" 
    db: 
      image: "mcr.microsoft.com/mssql/server" 
      environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
```
And here is how I would do it, please note I have added some comments to explain the changes"
```yaml
version: "3"
services:
    web: 
      build: . 
      ports: 
          - "8000:80" 
      depends_on: 
          - db 
      command: 
          - "sleep 5;" 
    db:
      # Latest version of SQL Server 2019 for Ubuntu 18.04
      image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
      environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
      # Adding container name to make sure connection string doesn't fails
      container_name: db
      # Adding port mapping, using 1433 as default
      ports:
          - "1433:1433"
```
Just keep in mind your, the connection string is pointing to the "master" database instead of your application database.

Regards,
