### ISSUE TITLE
Cannot put exist product id into docker using MSSQL_PID environment

### ISSUE THREAD

**Issue by ziitel2** [microsoft/mssql-docker#592]
### I always got this error after putting product id into my docker-compose.yml file.
```
ERROR: The provided PID [SDJ23-IASD1-97JJH-2NUH3-ASD14] is invalid.  The PID must be in the form #####-#####-#####-#####-##### where '#' is a number or letter.
```
### For my docker-compose.yml file look like this 
```
version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=SDJ23-IASD1-97JJH-2NUH3-ASD14
      - SA_PASSWORD=Testtest1
```
### I also try with
```
version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'SDJ23-IASD1-97JJH-2NUH3-ASD14'
      SA_PASSWOR: 'Testtest1'
```
Both single quote and double quote for value in environment show the same error.

### NOTE: the product id shown in the error is not the real one

**Comment by dbamaster** [comment]
Have you tried without quotation marks? I would try something like this:
```YAML
environment:
    ACCEPT_EULA: "Y"
    MSSQL_PID: "SDJ23-IASD1-97JJH-2NUH3-ASD14"
    SA_PASSWORD: "Testtest1"
```
I always use them in YAML files.

Cheers,
