### ISSUE TITLE
Log shipping not enabled in `2019-latest`

### ISSUE THREAD

**Issue by fitzoh** [microsoft/mssql-docker#595]
I'm attempting to test log replication in a 2019 docker image (specifically `d60e9ac97708`) and am receiving an error that is not present in the 2017 version about log shipping not being installed.

To replicate, spin up this docker-compose file:
```yaml
version: "3.3"
services:
  "2017":
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password!
      MSSQL_AGENT_ENABLED: "true"
    ports:
    - 1433:1433
  "2019":
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password!
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - 1434:1433
```

And execute this statement against both instances (port 1433 for 2017, 1444 for 2019)
```sql
sp_add_log_shipping_secondary_primary @primary_server = 'primary',
  @primary_database = 'test',
  @backup_source_directory = '/src',
  @backup_destination_directory = '/dst'
```

The 2017 version completes without error, while the 2019 version fails with the following message:

```
[2020-04-25 23:28:30] [S0003][32018] Log shipping is not installed on this instance.
[2020-04-25 23:28:30] [S0001][22001] RegQueryValueEx() returned error 2, 'The system cannot find the file specified.'
```
