### ISSUE TITLE
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)

### ISSUE THREAD

**Issue by neilmulhy** [microsoft/mssql-docker#602]
**Versions**

OS: Windows 10 Pro 64 Bit 1909 (18363.836)
Docker desktop version: 2.3.0.2 (45183)
Engine: 19.03.8
Compose: 1.25.5
Kubernetes: 1.16.5

I've successfully been using an MSSQL docker container for over a month now. It's based on image 'mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04' and auto starts up via docker-compose up using the following docker-compose.yml file:

```
version: "3"
services:
    sql1:
        image: "mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04"
        environment:
            SA_PASSWORD: "********"
            ACCEPT_EULA: "Y"
        volumes:
            - d:\dev\sqlserver\dbs:/var/opt/mssql/data
            - d:\dev\sqlserver\dbs\log:/var/opt/mssql/log
            - d:\dev\sqlserver\dbs\secrets:/var/opt/mssql/secrets
        ports:
            - "1433:1433"
        restart: always
```

Ever since I upgraded my Docker desktop version, to the one listed above, the container's constantly showing as restarting:
```docker container ls -a```

When I look at the container logs it's showing:
```
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
Your master database file is owned by root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)
```

I wasn't sure if this was a permissions issue but changing the yml to:
```
version: "3"
services:
    sql1:
        image: "mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04"
        environment:
            SA_PASSWORD: "********"
            ACCEPT_EULA: "Y"
        user: root
        volumes:
            - d:\dev\sqlserver\dbs:/var/opt/mssql/data
            - d:\dev\sqlserver\dbs\log:/var/opt/mssql/log
            - d:\dev\sqlserver\dbs\secrets:/var/opt/mssql/secrets
        ports:
            - "1433:1433"
        restart: always
```

Just ended up with the container restarting and the logs showing:
```
SQL Server 2019 will run as non-root by default.
This container is running as user root.
Your master database file is owned by root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)
```

I've done windows updates incase there was an update needed to run on the new version of docker desktop. I've also tried deleting the container and image but I'm still getting the same error and the container won't stay running.

I noticed someone else had the same error [here](https://github.com/microsoft/mssql-docker/issues/542) but this seemed to be linked to an issue declaring the volume name.

My issue is something stopping working that has been working well for a number of weeks.

Also, the other containers I have in docker are running as they were before the upgrade.

Any ideas?
