### ISSUE TITLE
SQL-Server 2019 docker container fails to start with -v option

### ISSUE THREAD

**Issue by ststeiger** [microsoft/mssql-docker#615]
I'm trying to run SQL-Server 2019 in docker in Ubuntu 18.04.

This is how I want it to look: 
```
mkdir -p /var/opt/mssql_2019
docker run -d -p 2019:1433 --name mssql_2019 -e 'MSSQL_SA_PASSWORD=TopSecret123456!abc' -e 'ACCEPT_EULA=Y' -e MSSQL_PID="Developer" -v /var/opt/mssql_2019:/var/opt/mssql -d mcr.microsoft.com/mssql/server:2019-latest
```

I issue the command, and sql-server exits immediately, not even an entry in the logfile in /var/opt/mssql_2019, hell, not even a file created there. 
If I omit 
`-v /var/opt/mssql_2019:/var/opt/mssql `

then it works fine. 

Doing exactly the same with sql-server 2017 worked fine. 

I run `docker logs <containterID>` and I get
```
SQL-Server 2019 will run as non-root by default. 
This container is running as user mssql. 
To learn more, visit...
/opt/mssql/bin/sqlservr: Error: The system directory [/.system] could not be created. Error [13].
```

I set permisson on /var/opt/mssql_2019 for group mssql to read&write...

Am I doing something wrong here, or is this a bug ? 

If this is a permission issue, how can I get the container to run as root ? 

If I switch to `su mssql`, I can create and delete files and folders in /var/opt/mssql_2019 without problems.

Also, if I add user mssql to sudo 
`adduser mssql sudo`
that doesn't help.

It should be noted that the docker file says
```
RUN useradd -M -s /bin/bash -u 10001 -g 0 mssql
RUN mkdir -p -m 770 /var/opt/mssql && chgrp -R 0 /var/opt/mssql
```

but on my computer, user mssql already exists as user 999...
Probably added by sql-server 2017...

**Comment by ststeiger** [comment]
Solved, don't know which one of the following did the trick

```
usermod --login mssql_2017 mssql
useradd -M -s /bin/bash -u 10001 -g 0 mssql

chgrp -R 0 /var/opt/mssql
chgrp -R 0 /var/opt/mssql_2019

```

from dockerfile exceprt in 
https://blog.dbi-services.com/using-non-root-sql-server-containers-on-docker-and-k8s/

**Comment by ststeiger** [comment]
Maybe it either should check if the user already exists, or it should create a separate user for every mssql-version.

**Comment by SonGokussj4** [comment]
`mkdir mssql && cd mssql`
`mkdir data`
`chown 10001 data`
Run container

Had to do this three times now because of permissions.

**Comment by mostafa8026** [comment]
I have this issue in k8s. :((
```
 # k logs mssql-57f6f78dbb-4jwwk
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
/opt/mssql/bin/sqlservr: Error: The system directory [/.system] could not be created.  Errno [13]
```

**Comment by mostafa8026** [comment]
Problem has been resolve with:
`chown 10001:0 [the-path-of-the-mounted-volume]`

**Comment by emmanuelcaamal** [comment]
I had de same problem, I solved it in the following way.

my docker compose was has follows 
```

sqlserver:
    container_name: "sqlserver"
    hostname: "sqlserver"
    image: "mcr.microsoft.com/mssql/server"
    environment: 
        SA_PASSWORD: "<my_password_here>"
        ACCEPT_EULA: "Y"
    ports:
        - 2533:1433
    volumes:
        - /var/lib/docker/volumes/mssql_db/_data:/var/opt/mssql
    expose:
        - 2533

```
and the change that applies was the following 

`- /var/lib/docker/volumes/mssql_db/_data:/var/opt/data`

finally this worked

**Comment by tmtiwari** [comment]
> I have this issue in k8s. :((
> 
> ```
>  # k logs mssql-57f6f78dbb-4jwwk
> SQL Server 2019 will run as non-root by default.
> This container is running as user mssql.
> To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
> /opt/mssql/bin/sqlservr: Error: The system directory [/.system] could not be created.  Errno [13]
> ```

And, when I change the mapping to `/var/opt/mssql/data` I get this :

```SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2021-01-15 23:50:05.95 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2021-01-15 23:50:06.05 Server      ERROR: Setup FAILED copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf':  2(The system cannot find the file specified.)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070002)
```

Why is an `Ubuntu` image looking in `C:` drive for template data?

**Comment by moh-hassan** [comment]
Using server:2019-latest, docker run fail with exited(2) ( docker version 20.10.5):
```
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=secret' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest -v L:\docker\sql-server\data:/var/opt/mssql/data  

```
Using docker compose **SUCCESS**:

```
version: '3.7'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: secret
            ACCEPT_EULA: Y
        ports:
            - '1433:1433'
        volumes: 
          - L:\docker\sql-server\data:/var/opt/mssql/data 
```
Note path in container: `/var/opt/mssql/data` 
I checked the local path: `L:\docker\sql-server\data` and find all mdf/ldf of database is created and connect successfully  using windows SQLCMD.

**Comment by IsaackRasmussen** [comment]
For Kubernetes: Adding the SecurityContext also works 
https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15
![image](https://user-images.githubusercontent.com/5748784/116829010-94892680-aba2-11eb-8209-9835e52bebba.png)

**Comment by IoTPlay** [comment]
What about rather running as another user? I cannot get this to work.

```
version: '3.6'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: mylinuxuser   # not as root
    ....
```

**Comment by amvin87** [comment]
@IoTPlay only the user mssql is supported to run SQL Server on Linux. See this sample for example: https://github.com/microsoft/mssql-docker/blob/master/linux/preview/SLES/dockerfile

**Comment by asadalidev** [comment]
> Problem has been resolve with running this command in the host:
> `chown 10001:0 [the-path-of-the-mounted-volume]`

it saved my time. Thanks

**Comment by alercunha** [comment]
In my case this error happened because the OS drive was full. Some how this translated to this error.
Just posting here in case someone is looking for an alternate solution.

**Comment by wodsonluiz** [comment]
My docker compose. Running on Macos with m1 processor

```
version: "3"
services:

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
      - SA_PASSWORD=mayPassword
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
       - compose-network

networks:
  compose-network:
    driver: bridge
```

**Comment by dieasmaz** [comment]
> I had the same problem, I solved it in the following way.
> 
> my docker compose was has follows
> 
> ```
> 
> sqlserver:
>     container_name: "sqlserver"
>     hostname: "sqlserver"
>     image: "mcr.microsoft.com/mssql/server"
>     environment: 
>         SA_PASSWORD: "<my_password_here>"
>         ACCEPT_EULA: "Y"
>     ports:
>         - 2533:1433
>     volumes:
>         - /var/lib/docker/volumes/mssql_db/_data:/var/opt/mssql
>     expose:
>         - 2533
> ```
> 
> and the change that applies was the following
> 
> `- /var/lib/docker/volumes/mssql_db/_data:/var/opt/data`
> 
> finally this worked

This works for me!
Thanks...

**Comment by tsondergaard** [comment]
When running with podman on RHEL 9 with selinux enabled, this is what fixed the problem for me:

```
chcon -t container_file_t /var/opt/mssql
```

**Comment by amirkochak** [comment]
> In my case this error happened because the OS drive was full. Somehow this error occurred because of that. Just posting here in case someone is looking for an alternate solution.

Resolved the issue for me.

**Comment by osnipezzini** [comment]
> Problem has been resolve with running this command in the host: `chown 10001:0 [the-path-of-the-mounted-volume]`

This solution fixed for me

**Comment by krillehbg** [comment]
For me it helped by setting the user:root


Part of my docker-compose
`version: '3.4'

services:
  mssql:
    container_name: mssql
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    user: root
    hostname: mssql
    networks:
      - proxy
    volumes:
    - /volume1/docker-data/mssql/data:/var/opt/mssql/data`

**Comment by m4ss1m0g** [comment]
For Docker Desktop, WSL2 and docker volumes the solution is:

1. run the image with -u 0:0 flag `docker run -u 0:0 ..... mcr.microsoft.com/mssql/server:2022-latest`
2. enter the container with bash and cd to `/var/opt`
3. run `chown -R 10001:0 mssql`
4. remove the container and re-start it *without* `-u 0:0`

**Comment by ryepup** [comment]
I ran into this using docker volumes, and didn't want to run mssql as root. where I can't easily chown. 

This is what I ended up with:

```yaml
version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always # keep trying, fix-perms might fix mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "<password>"
    volumes:
      - "mssql-data:/var/opt/mssql/data"

  # mssql has some weird defaults around permissions; fixup the volume to match
  fix-perms:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    command: chown -R mssql:root /var/opt/mssql
    volumes:
      - "mssql-data:/var/opt/mssql/data"

volumes:
  mssql-data:
```
