### ISSUE TITLE
login failed for sa

### ISSUE THREAD

**Issue by ninjaonsafari** [microsoft/mssql-docker#652]
I'm trying to run e2e test in my azure pipeline. But the services fail to start correctly because they cannot connect to the sql with following error:
```
 Error: 18456, Severity: 14, State: 7
 Login failed for user 'sa'. Reason: An error occurred while evaluating the password. [CLIENT: 172.18.0.9]
```
or
```
A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
```
The confusing part is, it only fails on the azure pipeline. On my local machine it works without any problems.
I already tried different passwords and connection strings. I run a linux container on azure pipelines and on my machine as well.

**docker-compose.yml:**
```
version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identity-api:
    image: ${REGISTRY:-PROJECTNAME}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqldata
```
**docker-compose.override.yml**
```
version: '3.4'

services:

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata;Database=IdentityDb;User Id=sa;Password=Pass@word
```
