### ISSUE TITLE
Cannot run with docker compose?

### ISSUE THREAD

**Issue by hrstoyanov** [microsoft/mssql-docker#674]
I build an image on top of the **2019-latest** (with some SSL additions).  I can connect to a container from my  image with any client (including JDBC):
```
docker run -e 'ACCEPT_EULA=Y' --name test -e 'SA_PASSWORD=Test!1234' -p 1434:1433 -d test/mssql:1.0 
```

However, if I start the  same image via docker compose:
```
docker-compose -f docker-compose.yml up
```
where **docker-compose.yml** is:
```
services:
  mssql:
    networks:
      - backend
    ports:
      - "1434:1433"
    image: test/mssql:1.0
    container_name: test_container
    hostname: test_container
    environment:
      - SА_PASSWORD=Test!1234 
      - ACCEPT_EULA=Y
networks:
    backend:
``` 

Clients **can no longer connect (password/user mismatch error)**? **I do not think my image causes this**, in fact you can use the stock ones with docker compose with the same outcome. Something is wrong with how docker compose sets env variables? What am I doing wrong?
