### ISSUE TITLE
Volumes Work on Docker for Mac

### ISSUE THREAD

**Issue by zhao-li** [microsoft/mssql-docker#686]
I'm not sure if the ["Known Issues"](https://hub.docker.com/_/microsoft-mssql-server?tab=description) about volumes not working on Docker for Mac is regarding another issue, but volumes is working for my Docker for Mac.

I am able to "persist" data between container start/stop by using the following Docker-Compose configuration:
```
version: '3.4'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
    volumes:
      - data:/var/opt/mssql/

volumes:
  data:
```

Version:
* Docker Desktop: 3.3.3 (64133)
* Engine: 20.10.6
* Compose: 1.29.1
* Kubernetes: v1.19.7
* Notary: 0.6.1
* Credential Helper: 0.6.3
* Snyk: v1.563.0

Hope that helps
