### ISSUE TITLE
Invalid environment variable between compose file and OS

### ISSUE THREAD

**Issue by Serfin** [microsoft/mssql-docker#691]
Hi,

During local setup of mssql I found something weird with password env variable. I'm using 'StrongPA$$WORD123!@#' as my value but the actual value that is set in OS is 'StrongPA$WORD123!@#'. Why is second $ skipped, is this a some sort of special characters escape?

img version- mcr.microsoft.com/mssql/server:latest

```
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: database
    ports:
      - "1433:1433"
    networks:
      - internal
    volumes:
      - db-data:/var/lib/mssql/data
    environment:
      - SA_PASSWORD=StrongPA$$WORD123!@#
      - ACCEPT_EULA=Y
      
networks:
  internal:
    name: internal-dev
    
volumes:
  db-data:
    driver: local
```

env inside container

![image](https://user-images.githubusercontent.com/23151526/120789851-6f396080-c532-11eb-90f5-a8cd50bff35e.png)
