### ISSUE TITLE
[mssql-tools] Unable to backup database 

### ISSUE THREAD

**Issue by ph3b** [microsoft/mssql-docker#720]
Hi!

I'm trying to back up a database using the `mcr.microsoft.com/mssql-tools` Docker image. I'm running the following command:

```$ sqlcmd -S db-host -U sa -P "password" -Q "BACKUP DATABASE [TestData] TO DISK = '/dump_data/backup-testdata.bak' WITH NOFORMAT, NOINIT, NAME = 'testdata', SKIP, NOREWIND, NOUNLOAD, STATS = 10"```

The target database is running in another container and I've ensured that it actually connects successfully.

The command fails with:

```
Msg 3201, Level 16, State 1, Server 7237b0dd4670, Line 1
Cannot open backup device '/dump_data/backup-test.bak'. Operating system error 5(Access is denied.).
Msg 3013, Level 16, State 1, Server 7237b0dd4670, Line 1
BACKUP DATABASE is terminating abnormally.
```
I've ensured that dump_data has correct permissions (chmod, chown) and even ran the container (and sqlcmd) as root. However, if I change the "TO DISK"-path to a folder that does not exist (or `/tmp`), it seems to complete successfully:

```
11 percent processed.
21 percent processed.
31 percent processed.
41 percent processed.
51 percent processed.
61 percent processed.
71 percent processed.
81 percent processed.
91 percent processed.
100 percent processed.
Processed 416 pages for database 'TestData', file 'TestData' on file 1.
Processed 2 pages for database 'TestData', file 'TestData_log' on file 1.
BACKUP DATABASE successfully processed 418 pages in 0.218 seconds (14.962 MB/sec).
```

Unfortunately, the folder and .bak-file is not actually created.

**docker-compose.yml**
```
version: "3.9"
services:
  master-db:
    volumes: 
      - ./data/db:/var/opt/mssql
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=mypassword!"
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
  db-cloner:
    environment:
      - "SA_PASSWORD=mypassword!"
    volumes: 
      - ./dump_data:/var/opt/mssql/data
    image: sqlcmd
    user: root
    command:  /opt/mssql-tools/bin/sqlcmd -S master-db,1433 -U sa -P "mypassword!" -Q "BACKUP DATABASE [TestData] TO DISK = '/var/opt/mssql/data/backup-test.bak' WITH NOFORMAT, NOINIT, NAME = 'test-full', SKIP, NOREWIND, NOUNLOAD, STATS = 10;"
    depends_on:
      master-db:
        condition: service_healthy

```

Any idea of what I'm doing wrong here? I'm hoping to be able to back the database up to a folder which is shared / mounted on my local machine. Running Mac OS 11.5.2.
