### ISSUE TITLE
BACKUP DATABASE TO URL with Azure Storage Emulator (Azurite) fails

### ISSUE THREAD

**Issue by Cogax** [microsoft/mssql-docker#721]
We use [https://github.com/Azure/Azurite](https://github.com/Azure/Azurite) as an emulator for Azure Blob Storage accounts in local and testing environments. We have an issue, that `BACKUP DATABASE TO URL` commands will fail if we use an URL to Azurite (`localhost`) and not `.blob.core.windows.net`:

```
System.Exception: Error on executing SQL Query: 'BACKUP DATABASE [RestoreTest] TO URL = 'http://127.0.0.1:20000/devstoreaccount1/baks/TestBackup.bak' WITH COMPRESSION, INIT, COPY_ONLY, FORMAT, MAXTRANSFERSIZE = 4194304, BLOCKSIZE = 65536, STATS = 5;' 
---> Microsoft.Data.SqlClient.SqlException: The file name "http://127.0.0.1:20000/devstoreaccount1/baks/TestBackup.bak" is invalid as a backup device name for the specified device type. Reissue the BACKUP statement with a valid file name and device type.
```

In Issue https://github.com/Azure/Azurite/issues/1089 we evaluated the problem and it seems not related to Azurite, but to mssql-server. 

#### C# Code:
```csharp
var uri = blobClient.GenerateSasUri(BlobSasPermissions.All, DateTimeOffset.UtcNow.AddHours(2));
var queryString = uri.Query;
var sasToken = queryString.Substring(1);
var blobUri = uri.AbsoluteUri.Replace(queryString, "");

var sqlDropCredential = $@"
  IF EXISTS (SELECT * from sys.credentials WHERE name = '{blobUri}')
      DROP CREDENTIAL [{blobUri}]";

var sqlCreateCredentials = @$"
    CREATE CREDENTIAL [{blobUri}] WITH IDENTITY = 'SHARED ACCESS SIGNATURE',
    SECRET = '{sasToken}'";

var sqlStartBackup = @$"
      BACKUP DATABASE [{databaseName}] TO URL = '{blobUri}'
      WITH COMPRESSION, INIT, COPY_ONLY, FORMAT, MAXTRANSFERSIZE = 4194304, BLOCKSIZE = 65536, STATS = 5;";
```

#### docker-compose.yaml
```
version: "2.4"
services:
  blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 20000:10000
      - 20001:10001
      - 20002:10002
    command: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0","--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "-d", "/data/debug.log"]
    volumes:
      -  /tmp/dat:/data
    healthcheck:
      test: nc -z localhost 10000 || exit -1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Top-Secret
      MSSQL_PID: Developer
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U sa -P Top-Secret || exit 1
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 15s
```
