### ISSUE TITLE
Unable to restore backup with in-memory optimized tables

### ISSUE THREAD

**Issue by zerouid** [microsoft/mssql-docker#767]
I have mcr.microsoft.com/mssql/server:latest image running on docker on macOS 12.4.
I use the following docker-compose.yml
```
version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: MsSqlServer
    environment:
      SA_PASSWORD: "<MySecretPWD>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbData:/var/opt/mssql
volumes:
  dbData:
```

When I try to restore a database backup 
that contains in-memory optimized tables I receive the following error.

```
Restore Database: Microsoft.Data.SqlClient.SqlError: The operating system returned the error '(null)' while attempting 'CreateFileW' on '/var/opt/mssql/data/Core.ndf/$FSLOG/fffff385-ffff5771-fff0.00000c7a-0000a88e-0009.1d601ff6-c0d7-4e63-b294-7bd0c551d04f~0bf3f7b5-ec86-41ba-8d88-539d15c56246~00000c7a-0000a88e-0009.2630bf-0.1000011'.
```
