### ISSUE TITLE
Failure to connect over docker network with hostname on Linux

### ISSUE THREAD

**Issue by ryanseipp** [microsoft/mssql-docker#788]
Hello, I have the following `docker-compose.yml` file which has been simplified. Other services in this dockerfile connect to this DB over the same network.
```yaml
version: '3.7'
services:
  mssql:
    container_name: mssql
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - test

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          ip_range: 172.18.0.0/24
          gateway: 172.18.0.1

```
After spinning this up, I try to connect using the following command:
```
docker run -it --rm --network test mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S tcp:mssql,5433 -U sa -P "${DB_PASSWORD}"
```
and receive the following error:
```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```
However, if I run the same connection command, but using the gateway IP:
```
docker run -it --rm --network test mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S 172.18.0.1,5433 -U sa -P "${DB_PASSWORD}"
```
Then `sqlcmd` is able to connect properly.

If I run the following command:
```
docker run -it --rm --network test nginx:1-alpine ping -c 3 mssql
```
then it resolves the IP of the `mssql` container correctly, and pings successfully.

Is there a reason why I cannot connect to the database using the hostname of the container? Am I missing something straightforward, or is this something that's not supported by your docker image? Note that I've tried with and without the `tcp:` prefix to the hostname and both return the same error. I have also tried with and without the custom network, instead relying on the default network `docker-compose` creates, also to the same effect.
