### ISSUE TITLE
Issue with mssql docker linux container AD

### ISSUE THREAD

**Issue by killmasta93** [microsoft/mssql-docker#808]
Hi I was wondering if someone else has had this issue before,
Currently trying to authenticate with LDAP using [How to Enable AD Authentication for SQL 2019 Containers in Less than 5 Minutes | Data Exposed - YouTube](https://www.youtube.com/watch?v=A0mn9928N48) as a guide with [Configure Active Directory authentication with SQL Server on Linux-based containers using adutil - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-containers-ad-auth-adutil-tutorial?view=sql-server-ver16)

the only thing different i changed is the docker compose file which im not sure if thats the issue,
I was checking the logs and couldn’t find information of the issue
the only issue im having is when i try to create the user

the ad server is 192.168.3.80

`create login [domain\administrator] From Windows
`

```
Msg 15401, Level 16, State 1, Line 1
Windows NT user or group 'domain\administrator' not found. Check the name again.
```

```
version: '3.7'
services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - "1433:1433"
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes:
          - /scsi3/sqlsystem:/var/opt/mssql/
          - /scsi3/sqldata:/var/opt/sqlserver/data
          - /scsi3/sqllog:/var/opt/sqlserver/log
          - /scsi3/sqlbackup:/var/opt/sqlserver/backup
          - /scsi3/krb5.conf:/etc/krb5.conf
        dns:
            - 192.168.0.80
        extra_hosts:
            - 'apolo.domain.local:192.168.3.80'
            - 'domain.local:192.168.3.80'

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
```

when i ssh into the container and ping apolo.domain.local it resolves correctly not sure what else i missed?
