### ISSUE TITLE
microsoft/mssql-server-linux:314918ddaedf doesn't start up on Debian server after upgrading to Debian Bookworm 12.0.0

### ISSUE THREAD

**Issue by stefangweichinger** [Microsoft/mssql-docker#845]
We run a small docker-compose-stack using "microsoft/mssql-server-linux     latest        314918ddaedf".

Today the docker host was upgraded from Debian 11.7 to Debian 12.0.0, since then the sqlserver-Container does not start up correctly:

```
sql1        | This program has encountered a fatal error and cannot continue running.
sql1        | The following diagnostic information is available:
sql1        | 
sql1        |        Reason: 0x00000003
sql1        |       Message: mappedBase == address
sql1        |    Stacktrace: 0000555f288abd55 0000555f288c6f5c 0000555f288c6c76 
sql1        |                0000555f288bbd84 0000555f288bbc91 0000555f288628d3 
      Process: 8 - sqlservr  
sql1        |        Thread: 98 (application thread 0x1158)
sql1        |   Instance Id: c0d9e52c-e32e-4d68-bb4f-848b9a59d937
sql1        |      Crash Id: af5484fc-6a79-4a99-b062-d7cecf481ceb
sql1        |   Build stamp: 7d599fe53e35b5a1b0c8a5e4185d8b7334e01a8c5fa77540415502a85f37ef27
sql1        | 
sql1        | Capturing core dump and information...
sql1        | find: '/proc/8/task/139': No such file or directory
sql1        | dmesg: read kernel buffer failed: Operation not permitted
sql1        | No journal files were found.
sql1        | No journal files were found.
sql1        | Attempting to capture a dump with paldumper
sql1 exited with code 1
```

`error.log` does not show anything problematic.

Relevant part of docker-compose.yml:

```
version: "3.4"
services:
  sql.data:
    # image: microsoft/mssql-server-linux:2017-latest
    image: microsoft/mssql-server-linux
    container_name: sql1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=xxxx
      - TZ=Europe/Vienna
    ports:
      - "1433:1433"
    volumes:
      - sql2data:/var/opt/mssql
      - sqlbackup:/backup
    ulimits:
      stack:
        soft: "8192000"
        hard: "8192000"
    networks:
      - front
```

The volumes are available in `/var/lib/docker` (ext4 filesystem).

The section "ulimits" was added by me trying to solve this.

```
# docker-compose --version
docker-compose version 1.25.4, build 8d51620a

# docker --version
Docker version 20.10.24+dfsg1, build 297e128
```

any help appreciated, the customer needs his intranet-application ... thanks
