### ISSUE TITLE
failed to pull and unpack image "mcr.microsoft.com/mssql/server:2019-latest"

### ISSUE THREAD

**Issue by robert-schmidtke** [microsoft/mssql-docker#846]
Hey, I am using the above image in my CI on Bitbucket, and since two weeks or so, I am getting the following error, which only vanishes after an increasing amount of retries:

```
rpc error: code = Unknown desc = failed to pull and unpack image "mcr.microsoft.com/mssql/server:2019-latest": failed to copy: read tcp 10.2.199.221:57304->204.79.197.219:443: read: connection reset by peer
```

Any idea what might be the issue here?

This is my definition according to https://support.atlassian.com/bitbucket-cloud/docs/databases-and-service-containers/#Define-a-service

```yaml
definitions:
  services:
    mssql0: &mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      memory: 6656
      variables:
        ACCEPT_EULA: Y
        MSSQL_PID: Developer
        MSSQL_SA_PASSWORD: Test1ng!
        MSSQL_TCP_PORT: 1433
```

Any help is much much appreciated!!

Thanks
Robert
