### ISSUE TITLE
MYSQL_PID=Developer not being set

### ISSUE THREAD

**Issue by lkdm** [Microsoft/mssql-docker#926]
Hi I'm new to Docker and SqlServer, and I'm trying to get a developer container working locally on my Ubuntu computer running Docker.

Setting `MYSQL_PID=Developer` environment variable is not respected by the container, and as a result it goes down as soon as it's created.

```Dockerfile
# mssql/Dockerfile
FROM mcr.microsoft.com/mssql/server:2022-latest
# Ensure SQL Server has permissions on its data directory
USER root
RUN mkdir -p /var/opt/mssql && chown -R mssql:mssql /var/opt/mssql
USER mssql
EXPOSE 1433
CMD ["/opt/mssql/bin/sqlservr"]
```

```yml
# docker-compose.yml
services:
  mssql:
    container_name: db_dev
    build:
      context: ./mssql
      dockerfile: Dockerfile
    image: my-org/my_proj-mssql:1.0
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD="MysuperStrongPasswordHere1!"
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - mynet
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "MysuperStrongPasswordHere1!" -Q "SELECT 1" || exit 1',
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
volumes:
  sqlvolume:
    driver: local
networks:
  mynet:
    name: my-network
    driver: bridge
```

Running `docker logs db_dev` outputs the following:

```
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2025-03-12 05:11:12.87 Server      ERROR: The provided PID [] is invalid.  The PID must be in the form #####-#####-#####-#####-##### where '#' is a number or letter.
```

Thank you in advance for your assistance.
